# Generated by Django 3.0.5 on 2020-06-07 04:00

import coffeehousemanager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StaffId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('JoinDate', models.DateField(auto_now_add=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Image', models.ImageField(upload_to=coffeehousemanager.models.upload_to_profile)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.CharField(blank=True, max_length=11, null=True)),
                ('Address', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to=coffeehousemanager.models.upload_to_product)),
                ('Price', models.FloatField()),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductType', to='coffeehousemanager.ProductType')),
            ],
        ),
    ]
