# Generated by Django 3.0.5 on 2020-06-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehousemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PositionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='Address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='JoinDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Position', to='coffeehousemanager.Position'),
        ),
    ]
